name: Update API Examples

on:
  push:
    branches:
      - main
      - task3

jobs:
  update-api-examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Task3
    env:
      TASK3_TOMORROW_IO_API_KEY: ${{ secrets.TASK3_TOMORROW_IO_API_KEY }}
      TASK3_OPEN_WEATHER_MAP_API_KEY: ${{ secrets.TASK3_OPEN_WEATHER_MAP_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Ensure Docker Service is Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost/health; do
            printf '.'
            sleep 5
          done

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch and Store API Responses
        run: |
          mkdir -p Task3/examples/responses
          chmod +x Task3/examples/requests/*.sh
          for script in Task3/examples/requests/*.sh; do
            (cd Task3/examples/requests && ./$script)
          done

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changes
        run: |
          git add Task3/examples/responses/*.json
          git commit -m "Update API examples"
          git push
