name: Update Swagger Documentation

on:
  push:
    branches:
      - main
      - task3

jobs:
  update-swagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Task3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Ensure Docker Service is Ready
        run: |
          timeout 600 bash -c 'until curl --output /dev/null --silent --head --fail \
          http://localhost/health; do printf "."; sleep 5; done'

      - name: Fetch Swagger JSON
        run: curl -o swagger.json http://localhost/swagger/v1/swagger.json

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changes
        run: |
          git add swagger.json
          git status
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'GitHub Actions Bot'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "Update Swagger documentation in Task3"
            # Pull-rebase and push loop
            while true; do
              git pull --rebase
              if git push; then
                echo "Push successful."
                break
              else
                echo "Push failed, retrying..."
                sleep 5
              fi
            done
          else
            echo "No changes to commit"
          fi
