name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['Task1', 'Task2', 'Task3']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }}/${{ matrix.project }}.sln
      - name: Build
        run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.sln
      - name: Test
        run: dotnet test ${{ matrix.project }}/Test/Test.csproj